print(len("navin karavde"))
print(len('coffee'))
length=len("Navin Karavde")
print("Your name has "+ str(length) + " characters")  
new_length=str(length)
print(type(new_length))
print(type(length))
print(length)
print("10" + "10")
print(int("10") + int("10"))